= HCD iTC
:showtitle:
:toc:
:imagesdir: images
:icons: font
:revnumber: 1.0
:revdate: 2022-10-17

:iTC-longname: Hardcopy Devices
:iTC-shortname: HCD-iTC
:iTC-email: kwangwoo.lee@hp.com
:iTC-website: https://hcd-itc.github.io/
:iTC-GitHub: https://github.com/HCD-iTC/

== Introduction
From the CCDB-established Working Group, the {iTC-longname} ({iTC-shortname} for short) was formed. The {iTC-shortname} consists of members of Certification Bodies, labs and vendors working together to create requirements for hardcopy devices security testing.

https://www.commoncriteriaportal.org/communities/hardcopy_devices.cfm[Common Criteria Portal {iTC-shortname} Page]

To join the {iTC-shortname}, please send a message to: {iTC-email}

== Current Status
The HCD-iTC has published the first Public Release of the collaborative Protection Profile (cPP) and Supporting Document (SD) as of Oct XX, 2022.

== Resources related to the {iTC-longname} iTC

[GUIDANCE]
====
Currently, the cPP and SD are available resources along with the GitHub repository. The iTC is working on updating this site with additional resources. 
====

* link:/cPP/cPP_HCD_V1.0.pdf[cPP v1.0]
* link:/SD/SD_HCD_V1.0.pdf[SD v1.0]
* {iTC-GitHub}[{iTC-shortname} GitHub repository]



